### ISSUE TITLE
在编辑图片时，该插件会自动拼接默认磁盘的域名

### ISSUE THREAD

**Issue by weifq** [tiderjian/la-filepond#5]
这一点如果只用后台那么没有任何问题，
但是在写前端接口时，会用到laravel的访问器来为图片添加域名。

**Comment by weifq** [comment]
这样一来，编辑图片时，就会覆盖两层域名，建议取消自动拼接这个操作

**Comment by tiderjian** [comment]
可以用disk方法来重新指定，不知是否能解决你的问题？

**Comment by weifq** [comment]
> 可以用磁盘方法来重新指定，不知是否能解决你的问题？

`Storage::disk('qiniu')->url('file1.jpg');`

**Comment by weifq** [comment]
> 可以用磁盘方法来重新指定，不知是否能解决你的问题？

我使用 `Storage::disk('qiniu')->url('file1.jpg');`

**Comment by weifq** [comment]
> 可以用磁盘方法来重新指定，不知是否能解决你的问题？

我使用 `Storage::disk('qiniu')->url('file1.jpg');`来重新指定，但是测试的结果是进入编辑页，图片依旧不能显示，检查元素发现连接为 `七牛域名/七牛域名/file1.jpg`

**Comment by weifq** [comment]
> 可以用disk方法来重新指定，不知是否能解决你的问题？

但是列表页使用的 $grid->image()  是可以正常显示的

**Comment by tiderjian** [comment]
你用的是七牛云存储吧？目前该插件还没考虑除了local形式的上传外的使用方式，后续可能会加上

**Comment by weifq** [comment]
> 你用的是七牛云存储吧？目前该插件还没考虑除了local形式的上传外的使用方式，后续可能会加上

👌
